// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// Request message sent by runC to sysvisorfs process during container
// registration, unregistration and update phases.
//
type ContainerData struct {
	Id                   string               `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	InitPid              int32                `protobuf:"varint,2,opt,name=InitPid,proto3" json:"InitPid,omitempty"`
	Hostname             string               `protobuf:"bytes,3,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Ctime                *timestamp.Timestamp `protobuf:"bytes,4,opt,name=Ctime,proto3" json:"Ctime,omitempty"`
	UidFirst             int32                `protobuf:"varint,5,opt,name=UidFirst,proto3" json:"UidFirst,omitempty"`
	UidSize              int32                `protobuf:"varint,6,opt,name=UidSize,proto3" json:"UidSize,omitempty"`
	GidFirst             int32                `protobuf:"varint,7,opt,name=GidFirst,proto3" json:"GidFirst,omitempty"`
	GidSize              int32                `protobuf:"varint,8,opt,name=GidSize,proto3" json:"GidSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ContainerData) Reset()         { *m = ContainerData{} }
func (m *ContainerData) String() string { return proto.CompactTextString(m) }
func (*ContainerData) ProtoMessage()    {}
func (*ContainerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{0}
}

func (m *ContainerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerData.Unmarshal(m, b)
}
func (m *ContainerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerData.Marshal(b, m, deterministic)
}
func (m *ContainerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerData.Merge(m, src)
}
func (m *ContainerData) XXX_Size() int {
	return xxx_messageInfo_ContainerData.Size(m)
}
func (m *ContainerData) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerData.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerData proto.InternalMessageInfo

func (m *ContainerData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ContainerData) GetInitPid() int32 {
	if m != nil {
		return m.InitPid
	}
	return 0
}

func (m *ContainerData) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ContainerData) GetCtime() *timestamp.Timestamp {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *ContainerData) GetUidFirst() int32 {
	if m != nil {
		return m.UidFirst
	}
	return 0
}

func (m *ContainerData) GetUidSize() int32 {
	if m != nil {
		return m.UidSize
	}
	return 0
}

func (m *ContainerData) GetGidFirst() int32 {
	if m != nil {
		return m.GidFirst
	}
	return 0
}

func (m *ContainerData) GetGidSize() int32 {
	if m != nil {
		return m.GidSize
	}
	return 0
}

// Response message sent from sysvisorfs to runC process.
type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*ContainerData)(nil), "protobuf.ContainerData")
	proto.RegisterType((*Response)(nil), "protobuf.Response")
}

func init() { proto.RegisterFile("protobuf.proto", fileDescriptor_c77a803fcbc0c059) }

var fileDescriptor_c77a803fcbc0c059 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcd, 0x4e, 0x02, 0x31,
	0x14, 0x85, 0x2d, 0x0a, 0x8c, 0x35, 0x62, 0xd2, 0x68, 0xa8, 0xb3, 0x91, 0x10, 0x13, 0x59, 0x0d,
	0x06, 0x5f, 0xc0, 0x80, 0xe1, 0x67, 0x47, 0x06, 0x79, 0x80, 0xc2, 0xd4, 0xf1, 0x26, 0xd0, 0x4e,
	0xda, 0x8b, 0x89, 0x3e, 0xb2, 0x5b, 0x5f, 0xc0, 0xcc, 0x94, 0x16, 0x5d, 0x1a, 0x77, 0xfd, 0x66,
	0xce, 0x39, 0xf7, 0xdc, 0xa6, 0xb4, 0x55, 0x18, 0x8d, 0x7a, 0xb5, 0x7b, 0x49, 0xaa, 0x03, 0x8b,
	0x3c, 0xc7, 0x37, 0xb9, 0xd6, 0xf9, 0x46, 0xf6, 0xfd, 0x87, 0x3e, 0xc2, 0x56, 0x5a, 0x14, 0xdb,
	0xc2, 0x49, 0xbb, 0x5f, 0x84, 0x9e, 0x8f, 0xb4, 0x42, 0x01, 0x4a, 0x9a, 0x27, 0x81, 0x82, 0xb5,
	0x68, 0x6d, 0x96, 0x71, 0xd2, 0x21, 0xbd, 0xd3, 0xb4, 0x36, 0xcb, 0x18, 0xa7, 0xcd, 0x99, 0x02,
	0x9c, 0x43, 0xc6, 0x6b, 0x1d, 0xd2, 0xab, 0xa7, 0x1e, 0x59, 0x4c, 0xa3, 0xa9, 0xb6, 0xa8, 0xc4,
	0x56, 0xf2, 0xe3, 0x4a, 0x1f, 0x98, 0xdd, 0xd3, 0xfa, 0xa8, 0x9c, 0xc5, 0x4f, 0x3a, 0xa4, 0x77,
	0x36, 0x88, 0x13, 0x57, 0x24, 0x09, 0x4d, 0x9f, 0x7d, 0x91, 0xd4, 0x09, 0xcb, 0xb4, 0x25, 0x64,
	0x63, 0x30, 0x16, 0x79, 0xbd, 0x1a, 0x14, 0xb8, 0xec, 0xb0, 0x84, 0x6c, 0x01, 0x1f, 0x92, 0x37,
	0x5c, 0x87, 0x3d, 0x96, 0xae, 0x89, 0x77, 0x35, 0x9d, 0x6b, 0xf2, 0xc3, 0x35, 0xd9, 0xbb, 0x22,
	0xe7, 0xda, 0x63, 0xf7, 0x96, 0x46, 0xa9, 0xb4, 0x85, 0x56, 0x56, 0x96, 0xaa, 0xc5, 0x6e, 0xbd,
	0x96, 0xd6, 0x56, 0x4b, 0x47, 0xa9, 0xc7, 0xc1, 0x27, 0xa1, 0x97, 0xf6, 0xdd, 0xbe, 0x81, 0xd5,
	0x66, 0x81, 0x02, 0xe5, 0xe8, 0x55, 0x28, 0x25, 0x37, 0x6c, 0x4c, 0xaf, 0xc2, 0x9d, 0xa5, 0x32,
	0x07, 0x8b, 0x46, 0x20, 0x68, 0xc5, 0xda, 0x87, 0xfd, 0x7e, 0x5d, 0x6a, 0xcc, 0x0e, 0x3f, 0xfc,
	0xe0, 0xee, 0x11, 0x9b, 0xd2, 0x76, 0x90, 0x2d, 0x95, 0xf9, 0x47, 0xd2, 0x23, 0xbd, 0x38, 0x24,
	0x15, 0x99, 0x40, 0xf9, 0xc7, 0x84, 0xe1, 0x1d, 0xbd, 0x06, 0x9d, 0xe4, 0xa6, 0x58, 0x27, 0x7e,
	0xe7, 0xa0, 0x1b, 0x86, 0x07, 0x35, 0x27, 0xab, 0x46, 0x75, 0x7e, 0xf8, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0xad, 0x5a, 0x51, 0x2e, 0x75, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SysvisorStateChannelClient is the client API for SysvisorStateChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SysvisorStateChannelClient interface {
	// Generates a container-registration message
	ContainerRegistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
	// Generates a container-unregistration message
	ContainerUnregistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
	// Generates a container-update message
	ContainerUpdate(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
}

type sysvisorStateChannelClient struct {
	cc *grpc.ClientConn
}

func NewSysvisorStateChannelClient(cc *grpc.ClientConn) SysvisorStateChannelClient {
	return &sysvisorStateChannelClient{cc}
}

func (c *sysvisorStateChannelClient) ContainerRegistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.sysvisorStateChannel/ContainerRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysvisorStateChannelClient) ContainerUnregistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.sysvisorStateChannel/ContainerUnregistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysvisorStateChannelClient) ContainerUpdate(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.sysvisorStateChannel/ContainerUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysvisorStateChannelServer is the server API for SysvisorStateChannel service.
type SysvisorStateChannelServer interface {
	// Generates a container-registration message
	ContainerRegistration(context.Context, *ContainerData) (*Response, error)
	// Generates a container-unregistration message
	ContainerUnregistration(context.Context, *ContainerData) (*Response, error)
	// Generates a container-update message
	ContainerUpdate(context.Context, *ContainerData) (*Response, error)
}

// UnimplementedSysvisorStateChannelServer can be embedded to have forward compatible implementations.
type UnimplementedSysvisorStateChannelServer struct {
}

func (*UnimplementedSysvisorStateChannelServer) ContainerRegistration(ctx context.Context, req *ContainerData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerRegistration not implemented")
}
func (*UnimplementedSysvisorStateChannelServer) ContainerUnregistration(ctx context.Context, req *ContainerData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerUnregistration not implemented")
}
func (*UnimplementedSysvisorStateChannelServer) ContainerUpdate(ctx context.Context, req *ContainerData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerUpdate not implemented")
}

func RegisterSysvisorStateChannelServer(s *grpc.Server, srv SysvisorStateChannelServer) {
	s.RegisterService(&_SysvisorStateChannel_serviceDesc, srv)
}

func _SysvisorStateChannel_ContainerRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysvisorStateChannelServer).ContainerRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.sysvisorStateChannel/ContainerRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysvisorStateChannelServer).ContainerRegistration(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysvisorStateChannel_ContainerUnregistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysvisorStateChannelServer).ContainerUnregistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.sysvisorStateChannel/ContainerUnregistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysvisorStateChannelServer).ContainerUnregistration(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysvisorStateChannel_ContainerUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysvisorStateChannelServer).ContainerUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.sysvisorStateChannel/ContainerUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysvisorStateChannelServer).ContainerUpdate(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

var _SysvisorStateChannel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.sysvisorStateChannel",
	HandlerType: (*SysvisorStateChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContainerRegistration",
			Handler:    _SysvisorStateChannel_ContainerRegistration_Handler,
		},
		{
			MethodName: "ContainerUnregistration",
			Handler:    _SysvisorStateChannel_ContainerUnregistration_Handler,
		},
		{
			MethodName: "ContainerUpdate",
			Handler:    _SysvisorStateChannel_ContainerUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf.proto",
}
