//
// Sysbox-fs Protobuffer Definitions.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: sysboxFsProtobuf.proto

package sysboxFsProtobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysboxStateChannel_GetMountpoint_FullMethodName            = "/protobuf.sysboxStateChannel/GetMountpoint"
	SysboxStateChannel_ContainerPreRegistration_FullMethodName = "/protobuf.sysboxStateChannel/ContainerPreRegistration"
	SysboxStateChannel_ContainerRegistration_FullMethodName    = "/protobuf.sysboxStateChannel/ContainerRegistration"
	SysboxStateChannel_ContainerUnregistration_FullMethodName  = "/protobuf.sysboxStateChannel/ContainerUnregistration"
	SysboxStateChannel_ContainerUpdate_FullMethodName          = "/protobuf.sysboxStateChannel/ContainerUpdate"
)

// SysboxStateChannelClient is the client API for SysboxStateChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContainerRegistration/Unregistration service definition.
type SysboxStateChannelClient interface {
	// Queries sysbox-fs for the FUSE mountpoint
	GetMountpoint(ctx context.Context, in *MountpointReq, opts ...grpc.CallOption) (*MountpointResp, error)
	// Generates a container-preregistration message
	ContainerPreRegistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
	// Generates a container-registration message
	ContainerRegistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
	// Generates a container-unregistration message
	ContainerUnregistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
	// Generates a container-update message
	ContainerUpdate(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
}

type sysboxStateChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewSysboxStateChannelClient(cc grpc.ClientConnInterface) SysboxStateChannelClient {
	return &sysboxStateChannelClient{cc}
}

func (c *sysboxStateChannelClient) GetMountpoint(ctx context.Context, in *MountpointReq, opts ...grpc.CallOption) (*MountpointResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountpointResp)
	err := c.cc.Invoke(ctx, SysboxStateChannel_GetMountpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxStateChannelClient) ContainerPreRegistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, SysboxStateChannel_ContainerPreRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxStateChannelClient) ContainerRegistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, SysboxStateChannel_ContainerRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxStateChannelClient) ContainerUnregistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, SysboxStateChannel_ContainerUnregistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxStateChannelClient) ContainerUpdate(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, SysboxStateChannel_ContainerUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysboxStateChannelServer is the server API for SysboxStateChannel service.
// All implementations must embed UnimplementedSysboxStateChannelServer
// for forward compatibility.
//
// ContainerRegistration/Unregistration service definition.
type SysboxStateChannelServer interface {
	// Queries sysbox-fs for the FUSE mountpoint
	GetMountpoint(context.Context, *MountpointReq) (*MountpointResp, error)
	// Generates a container-preregistration message
	ContainerPreRegistration(context.Context, *ContainerData) (*Response, error)
	// Generates a container-registration message
	ContainerRegistration(context.Context, *ContainerData) (*Response, error)
	// Generates a container-unregistration message
	ContainerUnregistration(context.Context, *ContainerData) (*Response, error)
	// Generates a container-update message
	ContainerUpdate(context.Context, *ContainerData) (*Response, error)
	mustEmbedUnimplementedSysboxStateChannelServer()
}

// UnimplementedSysboxStateChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysboxStateChannelServer struct{}

func (UnimplementedSysboxStateChannelServer) GetMountpoint(context.Context, *MountpointReq) (*MountpointResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMountpoint not implemented")
}
func (UnimplementedSysboxStateChannelServer) ContainerPreRegistration(context.Context, *ContainerData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerPreRegistration not implemented")
}
func (UnimplementedSysboxStateChannelServer) ContainerRegistration(context.Context, *ContainerData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerRegistration not implemented")
}
func (UnimplementedSysboxStateChannelServer) ContainerUnregistration(context.Context, *ContainerData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerUnregistration not implemented")
}
func (UnimplementedSysboxStateChannelServer) ContainerUpdate(context.Context, *ContainerData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerUpdate not implemented")
}
func (UnimplementedSysboxStateChannelServer) mustEmbedUnimplementedSysboxStateChannelServer() {}
func (UnimplementedSysboxStateChannelServer) testEmbeddedByValue()                            {}

// UnsafeSysboxStateChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysboxStateChannelServer will
// result in compilation errors.
type UnsafeSysboxStateChannelServer interface {
	mustEmbedUnimplementedSysboxStateChannelServer()
}

func RegisterSysboxStateChannelServer(s grpc.ServiceRegistrar, srv SysboxStateChannelServer) {
	// If the following call pancis, it indicates UnimplementedSysboxStateChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysboxStateChannel_ServiceDesc, srv)
}

func _SysboxStateChannel_GetMountpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountpointReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxStateChannelServer).GetMountpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxStateChannel_GetMountpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxStateChannelServer).GetMountpoint(ctx, req.(*MountpointReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxStateChannel_ContainerPreRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxStateChannelServer).ContainerPreRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxStateChannel_ContainerPreRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxStateChannelServer).ContainerPreRegistration(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxStateChannel_ContainerRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxStateChannelServer).ContainerRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxStateChannel_ContainerRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxStateChannelServer).ContainerRegistration(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxStateChannel_ContainerUnregistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxStateChannelServer).ContainerUnregistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxStateChannel_ContainerUnregistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxStateChannelServer).ContainerUnregistration(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxStateChannel_ContainerUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxStateChannelServer).ContainerUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxStateChannel_ContainerUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxStateChannelServer).ContainerUpdate(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

// SysboxStateChannel_ServiceDesc is the grpc.ServiceDesc for SysboxStateChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysboxStateChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.sysboxStateChannel",
	HandlerType: (*SysboxStateChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMountpoint",
			Handler:    _SysboxStateChannel_GetMountpoint_Handler,
		},
		{
			MethodName: "ContainerPreRegistration",
			Handler:    _SysboxStateChannel_ContainerPreRegistration_Handler,
		},
		{
			MethodName: "ContainerRegistration",
			Handler:    _SysboxStateChannel_ContainerRegistration_Handler,
		},
		{
			MethodName: "ContainerUnregistration",
			Handler:    _SysboxStateChannel_ContainerUnregistration_Handler,
		},
		{
			MethodName: "ContainerUpdate",
			Handler:    _SysboxStateChannel_ContainerUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sysboxFsProtobuf.proto",
}
