//
// SysboxMgr Protobuffer Definitions.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: sysboxMgrProtobuf.proto

package sysboxMgrProtobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysboxMgrStateChannel_Register_FullMethodName                = "/protobuf.sysboxMgrStateChannel/Register"
	SysboxMgrStateChannel_Update_FullMethodName                  = "/protobuf.sysboxMgrStateChannel/Update"
	SysboxMgrStateChannel_Unregister_FullMethodName              = "/protobuf.sysboxMgrStateChannel/Unregister"
	SysboxMgrStateChannel_SubidAlloc_FullMethodName              = "/protobuf.sysboxMgrStateChannel/SubidAlloc"
	SysboxMgrStateChannel_PrepMounts_FullMethodName              = "/protobuf.sysboxMgrStateChannel/PrepMounts"
	SysboxMgrStateChannel_ReqMounts_FullMethodName               = "/protobuf.sysboxMgrStateChannel/ReqMounts"
	SysboxMgrStateChannel_ReqShiftfsMark_FullMethodName          = "/protobuf.sysboxMgrStateChannel/ReqShiftfsMark"
	SysboxMgrStateChannel_ReqFsState_FullMethodName              = "/protobuf.sysboxMgrStateChannel/ReqFsState"
	SysboxMgrStateChannel_SetupDevices_FullMethodName            = "/protobuf.sysboxMgrStateChannel/SetupDevices"
	SysboxMgrStateChannel_Pause_FullMethodName                   = "/protobuf.sysboxMgrStateChannel/Pause"
	SysboxMgrStateChannel_Resume_FullMethodName                  = "/protobuf.sysboxMgrStateChannel/Resume"
	SysboxMgrStateChannel_ReqCloneRootfs_FullMethodName          = "/protobuf.sysboxMgrStateChannel/ReqCloneRootfs"
	SysboxMgrStateChannel_ChownClonedRootfs_FullMethodName       = "/protobuf.sysboxMgrStateChannel/ChownClonedRootfs"
	SysboxMgrStateChannel_RevertClonedRootfsChown_FullMethodName = "/protobuf.sysboxMgrStateChannel/RevertClonedRootfsChown"
)

// SysboxMgrStateChannelClient is the client API for SysboxMgrStateChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// sysboxMgr channel
type SysboxMgrStateChannelClient interface {
	// Container registration
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	// Container Update
	Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateResp, error)
	// Container Unregistration
	Unregister(ctx context.Context, in *UnregisterReq, opts ...grpc.CallOption) (*UnregisterResp, error)
	// Subuid(gid) allocation request
	SubidAlloc(ctx context.Context, in *SubidAllocReq, opts ...grpc.CallOption) (*SubidAllocResp, error)
	// Mount source prep request
	PrepMounts(ctx context.Context, in *MountPrepReq, opts ...grpc.CallOption) (*MountPrepResp, error)
	// Mount request
	ReqMounts(ctx context.Context, in *MountReq, opts ...grpc.CallOption) (*MountResp, error)
	// Shiftfs mark request
	ReqShiftfsMark(ctx context.Context, in *ShiftfsMarkReq, opts ...grpc.CallOption) (*ShiftfsMarkResp, error)
	// FsState request
	ReqFsState(ctx context.Context, in *FsStateReq, opts ...grpc.CallOption) (*FsStateResp, error)
	// Device setup request
	SetupDevices(ctx context.Context, in *DeviceSetupReq, opts ...grpc.CallOption) (*DeviceSetupResp, error)
	// Pause request
	Pause(ctx context.Context, in *PauseReq, opts ...grpc.CallOption) (*PauseResp, error)
	// Resume request
	Resume(ctx context.Context, in *ResumeReq, opts ...grpc.CallOption) (*ResumeResp, error)
	// Clone rootfs request
	ReqCloneRootfs(ctx context.Context, in *CloneRootfsReq, opts ...grpc.CallOption) (*CloneRootfsResp, error)
	// Chown cloned rootfs request
	ChownClonedRootfs(ctx context.Context, in *ChownClonedRootfsReq, opts ...grpc.CallOption) (*ChownClonedRootfsResp, error)
	// Revert cloned rootfs chown
	RevertClonedRootfsChown(ctx context.Context, in *RevertClonedRootfsChownReq, opts ...grpc.CallOption) (*RevertClonedRootfsChownResp, error)
}

type sysboxMgrStateChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewSysboxMgrStateChannelClient(cc grpc.ClientConnInterface) SysboxMgrStateChannelClient {
	return &sysboxMgrStateChannelClient{cc}
}

func (c *sysboxMgrStateChannelClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) Unregister(ctx context.Context, in *UnregisterReq, opts ...grpc.CallOption) (*UnregisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_Unregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) SubidAlloc(ctx context.Context, in *SubidAllocReq, opts ...grpc.CallOption) (*SubidAllocResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubidAllocResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_SubidAlloc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) PrepMounts(ctx context.Context, in *MountPrepReq, opts ...grpc.CallOption) (*MountPrepResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountPrepResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_PrepMounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) ReqMounts(ctx context.Context, in *MountReq, opts ...grpc.CallOption) (*MountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_ReqMounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) ReqShiftfsMark(ctx context.Context, in *ShiftfsMarkReq, opts ...grpc.CallOption) (*ShiftfsMarkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShiftfsMarkResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_ReqShiftfsMark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) ReqFsState(ctx context.Context, in *FsStateReq, opts ...grpc.CallOption) (*FsStateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FsStateResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_ReqFsState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) SetupDevices(ctx context.Context, in *DeviceSetupReq, opts ...grpc.CallOption) (*DeviceSetupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceSetupResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_SetupDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) Pause(ctx context.Context, in *PauseReq, opts ...grpc.CallOption) (*PauseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) Resume(ctx context.Context, in *ResumeReq, opts ...grpc.CallOption) (*ResumeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) ReqCloneRootfs(ctx context.Context, in *CloneRootfsReq, opts ...grpc.CallOption) (*CloneRootfsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneRootfsResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_ReqCloneRootfs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) ChownClonedRootfs(ctx context.Context, in *ChownClonedRootfsReq, opts ...grpc.CallOption) (*ChownClonedRootfsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChownClonedRootfsResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_ChownClonedRootfs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxMgrStateChannelClient) RevertClonedRootfsChown(ctx context.Context, in *RevertClonedRootfsChownReq, opts ...grpc.CallOption) (*RevertClonedRootfsChownResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevertClonedRootfsChownResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_RevertClonedRootfsChown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysboxMgrStateChannelServer is the server API for SysboxMgrStateChannel service.
// All implementations must embed UnimplementedSysboxMgrStateChannelServer
// for forward compatibility.
//
// sysboxMgr channel
type SysboxMgrStateChannelServer interface {
	// Container registration
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	// Container Update
	Update(context.Context, *UpdateReq) (*UpdateResp, error)
	// Container Unregistration
	Unregister(context.Context, *UnregisterReq) (*UnregisterResp, error)
	// Subuid(gid) allocation request
	SubidAlloc(context.Context, *SubidAllocReq) (*SubidAllocResp, error)
	// Mount source prep request
	PrepMounts(context.Context, *MountPrepReq) (*MountPrepResp, error)
	// Mount request
	ReqMounts(context.Context, *MountReq) (*MountResp, error)
	// Shiftfs mark request
	ReqShiftfsMark(context.Context, *ShiftfsMarkReq) (*ShiftfsMarkResp, error)
	// FsState request
	ReqFsState(context.Context, *FsStateReq) (*FsStateResp, error)
	// Device setup request
	SetupDevices(context.Context, *DeviceSetupReq) (*DeviceSetupResp, error)
	// Pause request
	Pause(context.Context, *PauseReq) (*PauseResp, error)
	// Resume request
	Resume(context.Context, *ResumeReq) (*ResumeResp, error)
	// Clone rootfs request
	ReqCloneRootfs(context.Context, *CloneRootfsReq) (*CloneRootfsResp, error)
	// Chown cloned rootfs request
	ChownClonedRootfs(context.Context, *ChownClonedRootfsReq) (*ChownClonedRootfsResp, error)
	// Revert cloned rootfs chown
	RevertClonedRootfsChown(context.Context, *RevertClonedRootfsChownReq) (*RevertClonedRootfsChownResp, error)
	mustEmbedUnimplementedSysboxMgrStateChannelServer()
}

// UnimplementedSysboxMgrStateChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysboxMgrStateChannelServer struct{}

func (UnimplementedSysboxMgrStateChannelServer) Register(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) Update(context.Context, *UpdateReq) (*UpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) Unregister(context.Context, *UnregisterReq) (*UnregisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) SubidAlloc(context.Context, *SubidAllocReq) (*SubidAllocResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubidAlloc not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) PrepMounts(context.Context, *MountPrepReq) (*MountPrepResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepMounts not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) ReqMounts(context.Context, *MountReq) (*MountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqMounts not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) ReqShiftfsMark(context.Context, *ShiftfsMarkReq) (*ShiftfsMarkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqShiftfsMark not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) ReqFsState(context.Context, *FsStateReq) (*FsStateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqFsState not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) SetupDevices(context.Context, *DeviceSetupReq) (*DeviceSetupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupDevices not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) Pause(context.Context, *PauseReq) (*PauseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) Resume(context.Context, *ResumeReq) (*ResumeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) ReqCloneRootfs(context.Context, *CloneRootfsReq) (*CloneRootfsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqCloneRootfs not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) ChownClonedRootfs(context.Context, *ChownClonedRootfsReq) (*ChownClonedRootfsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChownClonedRootfs not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) RevertClonedRootfsChown(context.Context, *RevertClonedRootfsChownReq) (*RevertClonedRootfsChownResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevertClonedRootfsChown not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) mustEmbedUnimplementedSysboxMgrStateChannelServer() {}
func (UnimplementedSysboxMgrStateChannelServer) testEmbeddedByValue()                               {}

// UnsafeSysboxMgrStateChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysboxMgrStateChannelServer will
// result in compilation errors.
type UnsafeSysboxMgrStateChannelServer interface {
	mustEmbedUnimplementedSysboxMgrStateChannelServer()
}

func RegisterSysboxMgrStateChannelServer(s grpc.ServiceRegistrar, srv SysboxMgrStateChannelServer) {
	// If the following call pancis, it indicates UnimplementedSysboxMgrStateChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysboxMgrStateChannel_ServiceDesc, srv)
}

func _SysboxMgrStateChannel_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).Update(ctx, req.(*UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).Unregister(ctx, req.(*UnregisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_SubidAlloc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubidAllocReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).SubidAlloc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_SubidAlloc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).SubidAlloc(ctx, req.(*SubidAllocReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_PrepMounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountPrepReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).PrepMounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_PrepMounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).PrepMounts(ctx, req.(*MountPrepReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_ReqMounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).ReqMounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_ReqMounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).ReqMounts(ctx, req.(*MountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_ReqShiftfsMark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShiftfsMarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).ReqShiftfsMark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_ReqShiftfsMark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).ReqShiftfsMark(ctx, req.(*ShiftfsMarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_ReqFsState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FsStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).ReqFsState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_ReqFsState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).ReqFsState(ctx, req.(*FsStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_SetupDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceSetupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).SetupDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_SetupDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).SetupDevices(ctx, req.(*DeviceSetupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).Pause(ctx, req.(*PauseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).Resume(ctx, req.(*ResumeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_ReqCloneRootfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneRootfsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).ReqCloneRootfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_ReqCloneRootfs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).ReqCloneRootfs(ctx, req.(*CloneRootfsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_ChownClonedRootfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChownClonedRootfsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).ChownClonedRootfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_ChownClonedRootfs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).ChownClonedRootfs(ctx, req.(*ChownClonedRootfsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxMgrStateChannel_RevertClonedRootfsChown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevertClonedRootfsChownReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).RevertClonedRootfsChown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_RevertClonedRootfsChown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).RevertClonedRootfsChown(ctx, req.(*RevertClonedRootfsChownReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SysboxMgrStateChannel_ServiceDesc is the grpc.ServiceDesc for SysboxMgrStateChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysboxMgrStateChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.sysboxMgrStateChannel",
	HandlerType: (*SysboxMgrStateChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _SysboxMgrStateChannel_Register_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SysboxMgrStateChannel_Update_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _SysboxMgrStateChannel_Unregister_Handler,
		},
		{
			MethodName: "SubidAlloc",
			Handler:    _SysboxMgrStateChannel_SubidAlloc_Handler,
		},
		{
			MethodName: "PrepMounts",
			Handler:    _SysboxMgrStateChannel_PrepMounts_Handler,
		},
		{
			MethodName: "ReqMounts",
			Handler:    _SysboxMgrStateChannel_ReqMounts_Handler,
		},
		{
			MethodName: "ReqShiftfsMark",
			Handler:    _SysboxMgrStateChannel_ReqShiftfsMark_Handler,
		},
		{
			MethodName: "ReqFsState",
			Handler:    _SysboxMgrStateChannel_ReqFsState_Handler,
		},
		{
			MethodName: "SetupDevices",
			Handler:    _SysboxMgrStateChannel_SetupDevices_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _SysboxMgrStateChannel_Pause_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _SysboxMgrStateChannel_Resume_Handler,
		},
		{
			MethodName: "ReqCloneRootfs",
			Handler:    _SysboxMgrStateChannel_ReqCloneRootfs_Handler,
		},
		{
			MethodName: "ChownClonedRootfs",
			Handler:    _SysboxMgrStateChannel_ChownClonedRootfs_Handler,
		},
		{
			MethodName: "RevertClonedRootfsChown",
			Handler:    _SysboxMgrStateChannel_RevertClonedRootfsChown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sysboxMgrProtobuf.proto",
}
