// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubidAllocReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubidAllocReq) Reset()         { *m = SubidAllocReq{} }
func (m *SubidAllocReq) String() string { return proto.CompactTextString(m) }
func (*SubidAllocReq) ProtoMessage()    {}
func (*SubidAllocReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{0}
}

func (m *SubidAllocReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubidAllocReq.Unmarshal(m, b)
}
func (m *SubidAllocReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubidAllocReq.Marshal(b, m, deterministic)
}
func (m *SubidAllocReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubidAllocReq.Merge(m, src)
}
func (m *SubidAllocReq) XXX_Size() int {
	return xxx_messageInfo_SubidAllocReq.Size(m)
}
func (m *SubidAllocReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SubidAllocReq.DiscardUnknown(m)
}

var xxx_messageInfo_SubidAllocReq proto.InternalMessageInfo

func (m *SubidAllocReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SubidAllocReq) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type SubidAllocResp struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint32   `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubidAllocResp) Reset()         { *m = SubidAllocResp{} }
func (m *SubidAllocResp) String() string { return proto.CompactTextString(m) }
func (*SubidAllocResp) ProtoMessage()    {}
func (*SubidAllocResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{1}
}

func (m *SubidAllocResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubidAllocResp.Unmarshal(m, b)
}
func (m *SubidAllocResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubidAllocResp.Marshal(b, m, deterministic)
}
func (m *SubidAllocResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubidAllocResp.Merge(m, src)
}
func (m *SubidAllocResp) XXX_Size() int {
	return xxx_messageInfo_SubidAllocResp.Size(m)
}
func (m *SubidAllocResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SubidAllocResp.DiscardUnknown(m)
}

var xxx_messageInfo_SubidAllocResp proto.InternalMessageInfo

func (m *SubidAllocResp) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SubidAllocResp) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type SubidFreeReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubidFreeReq) Reset()         { *m = SubidFreeReq{} }
func (m *SubidFreeReq) String() string { return proto.CompactTextString(m) }
func (*SubidFreeReq) ProtoMessage()    {}
func (*SubidFreeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{2}
}

func (m *SubidFreeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubidFreeReq.Unmarshal(m, b)
}
func (m *SubidFreeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubidFreeReq.Marshal(b, m, deterministic)
}
func (m *SubidFreeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubidFreeReq.Merge(m, src)
}
func (m *SubidFreeReq) XXX_Size() int {
	return xxx_messageInfo_SubidFreeReq.Size(m)
}
func (m *SubidFreeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SubidFreeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SubidFreeReq proto.InternalMessageInfo

func (m *SubidFreeReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SubidFreeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubidFreeResp) Reset()         { *m = SubidFreeResp{} }
func (m *SubidFreeResp) String() string { return proto.CompactTextString(m) }
func (*SubidFreeResp) ProtoMessage()    {}
func (*SubidFreeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{3}
}

func (m *SubidFreeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubidFreeResp.Unmarshal(m, b)
}
func (m *SubidFreeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubidFreeResp.Marshal(b, m, deterministic)
}
func (m *SubidFreeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubidFreeResp.Merge(m, src)
}
func (m *SubidFreeResp) XXX_Size() int {
	return xxx_messageInfo_SubidFreeResp.Size(m)
}
func (m *SubidFreeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SubidFreeResp.DiscardUnknown(m)
}

var xxx_messageInfo_SubidFreeResp proto.InternalMessageInfo

type Mount struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Dest                 string   `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Opt                  []string `protobuf:"bytes,4,rep,name=opt,proto3" json:"opt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mount) Reset()         { *m = Mount{} }
func (m *Mount) String() string { return proto.CompactTextString(m) }
func (*Mount) ProtoMessage()    {}
func (*Mount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{4}
}

func (m *Mount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mount.Unmarshal(m, b)
}
func (m *Mount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mount.Marshal(b, m, deterministic)
}
func (m *Mount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mount.Merge(m, src)
}
func (m *Mount) XXX_Size() int {
	return xxx_messageInfo_Mount.Size(m)
}
func (m *Mount) XXX_DiscardUnknown() {
	xxx_messageInfo_Mount.DiscardUnknown(m)
}

var xxx_messageInfo_Mount proto.InternalMessageInfo

func (m *Mount) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Mount) GetDest() string {
	if m != nil {
		return m.Dest
	}
	return ""
}

func (m *Mount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Mount) GetOpt() []string {
	if m != nil {
		return m.Opt
	}
	return nil
}

type SupMountsReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rootfs               string   `protobuf:"bytes,2,opt,name=rootfs,proto3" json:"rootfs,omitempty"`
	Uid                  uint32   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint32   `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	ShiftUids            bool     `protobuf:"varint,5,opt,name=shiftUids,proto3" json:"shiftUids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupMountsReq) Reset()         { *m = SupMountsReq{} }
func (m *SupMountsReq) String() string { return proto.CompactTextString(m) }
func (*SupMountsReq) ProtoMessage()    {}
func (*SupMountsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{5}
}

func (m *SupMountsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupMountsReq.Unmarshal(m, b)
}
func (m *SupMountsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupMountsReq.Marshal(b, m, deterministic)
}
func (m *SupMountsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupMountsReq.Merge(m, src)
}
func (m *SupMountsReq) XXX_Size() int {
	return xxx_messageInfo_SupMountsReq.Size(m)
}
func (m *SupMountsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SupMountsReq.DiscardUnknown(m)
}

var xxx_messageInfo_SupMountsReq proto.InternalMessageInfo

func (m *SupMountsReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SupMountsReq) GetRootfs() string {
	if m != nil {
		return m.Rootfs
	}
	return ""
}

func (m *SupMountsReq) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SupMountsReq) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *SupMountsReq) GetShiftUids() bool {
	if m != nil {
		return m.ShiftUids
	}
	return false
}

type SupMountsReqResp struct {
	Mounts               []*Mount `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupMountsReqResp) Reset()         { *m = SupMountsReqResp{} }
func (m *SupMountsReqResp) String() string { return proto.CompactTextString(m) }
func (*SupMountsReqResp) ProtoMessage()    {}
func (*SupMountsReqResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{6}
}

func (m *SupMountsReqResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupMountsReqResp.Unmarshal(m, b)
}
func (m *SupMountsReqResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupMountsReqResp.Marshal(b, m, deterministic)
}
func (m *SupMountsReqResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupMountsReqResp.Merge(m, src)
}
func (m *SupMountsReqResp) XXX_Size() int {
	return xxx_messageInfo_SupMountsReqResp.Size(m)
}
func (m *SupMountsReqResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SupMountsReqResp.DiscardUnknown(m)
}

var xxx_messageInfo_SupMountsReqResp proto.InternalMessageInfo

func (m *SupMountsReqResp) GetMounts() []*Mount {
	if m != nil {
		return m.Mounts
	}
	return nil
}

type SupMountsRel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupMountsRel) Reset()         { *m = SupMountsRel{} }
func (m *SupMountsRel) String() string { return proto.CompactTextString(m) }
func (*SupMountsRel) ProtoMessage()    {}
func (*SupMountsRel) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{7}
}

func (m *SupMountsRel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupMountsRel.Unmarshal(m, b)
}
func (m *SupMountsRel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupMountsRel.Marshal(b, m, deterministic)
}
func (m *SupMountsRel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupMountsRel.Merge(m, src)
}
func (m *SupMountsRel) XXX_Size() int {
	return xxx_messageInfo_SupMountsRel.Size(m)
}
func (m *SupMountsRel) XXX_DiscardUnknown() {
	xxx_messageInfo_SupMountsRel.DiscardUnknown(m)
}

var xxx_messageInfo_SupMountsRel proto.InternalMessageInfo

func (m *SupMountsRel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SupMountsRelResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupMountsRelResp) Reset()         { *m = SupMountsRelResp{} }
func (m *SupMountsRelResp) String() string { return proto.CompactTextString(m) }
func (*SupMountsRelResp) ProtoMessage()    {}
func (*SupMountsRelResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c77a803fcbc0c059, []int{8}
}

func (m *SupMountsRelResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupMountsRelResp.Unmarshal(m, b)
}
func (m *SupMountsRelResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupMountsRelResp.Marshal(b, m, deterministic)
}
func (m *SupMountsRelResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupMountsRelResp.Merge(m, src)
}
func (m *SupMountsRelResp) XXX_Size() int {
	return xxx_messageInfo_SupMountsRelResp.Size(m)
}
func (m *SupMountsRelResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SupMountsRelResp.DiscardUnknown(m)
}

var xxx_messageInfo_SupMountsRelResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SubidAllocReq)(nil), "protobuf.SubidAllocReq")
	proto.RegisterType((*SubidAllocResp)(nil), "protobuf.SubidAllocResp")
	proto.RegisterType((*SubidFreeReq)(nil), "protobuf.SubidFreeReq")
	proto.RegisterType((*SubidFreeResp)(nil), "protobuf.SubidFreeResp")
	proto.RegisterType((*Mount)(nil), "protobuf.Mount")
	proto.RegisterType((*SupMountsReq)(nil), "protobuf.SupMountsReq")
	proto.RegisterType((*SupMountsReqResp)(nil), "protobuf.SupMountsReqResp")
	proto.RegisterType((*SupMountsRel)(nil), "protobuf.SupMountsRel")
	proto.RegisterType((*SupMountsRelResp)(nil), "protobuf.SupMountsRelResp")
}

func init() { proto.RegisterFile("protobuf.proto", fileDescriptor_c77a803fcbc0c059) }

var fileDescriptor_c77a803fcbc0c059 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x8f, 0xda, 0x30,
	0x10, 0x6d, 0x3e, 0x36, 0xda, 0x4c, 0x17, 0x76, 0xe5, 0x03, 0xa4, 0x51, 0x55, 0x45, 0xbe, 0x6c,
	0x4e, 0x39, 0x40, 0x6f, 0x95, 0x2a, 0x41, 0xab, 0xde, 0x90, 0x2a, 0xa3, 0x1e, 0x7a, 0x04, 0x62,
	0xc0, 0x92, 0x8b, 0x4d, 0xec, 0x54, 0xa5, 0xbf, 0xa8, 0x3f, 0xb3, 0xb2, 0x63, 0x12, 0x28, 0xa9,
	0xf6, 0xf6, 0xfc, 0x66, 0xde, 0x9b, 0xaf, 0x04, 0x86, 0xb2, 0x12, 0x5a, 0xac, 0xeb, 0x6d, 0x61,
	0x01, 0xba, 0x3f, 0xbf, 0xf1, 0x14, 0x06, 0xcb, 0x7a, 0xcd, 0xca, 0x19, 0xe7, 0x62, 0x43, 0xe8,
	0x11, 0x0d, 0xc1, 0x67, 0x65, 0xe2, 0x65, 0x5e, 0x1e, 0x13, 0x9f, 0x95, 0x08, 0x41, 0xa8, 0xd8,
	0x6f, 0x9a, 0xf8, 0x99, 0x97, 0x87, 0xc4, 0x62, 0xfc, 0x1e, 0x86, 0x97, 0x22, 0x25, 0xd1, 0x13,
	0x04, 0xb5, 0x93, 0x0d, 0x88, 0x81, 0x86, 0xd9, 0xb1, 0xd2, 0xca, 0x06, 0xc4, 0x40, 0xfc, 0x0e,
	0x1e, 0xac, 0xea, 0x4b, 0x45, 0x69, 0x4f, 0x25, 0xfc, 0xe8, 0x5a, 0x69, 0xe2, 0x4a, 0xe2, 0xef,
	0x70, 0xb7, 0x10, 0xf5, 0x41, 0xa3, 0x11, 0x44, 0x4a, 0xd4, 0xd5, 0x86, 0xba, 0x6c, 0xf7, 0x32,
	0xbd, 0x95, 0x54, 0x69, 0x5b, 0x24, 0x26, 0x16, 0x1b, 0x4e, 0x9f, 0x24, 0x4d, 0x82, 0x86, 0x33,
	0xd8, 0xf4, 0x22, 0xa4, 0x4e, 0xc2, 0x2c, 0xc8, 0x63, 0x62, 0x20, 0xfe, 0x65, 0x7a, 0x91, 0xd6,
	0x5d, 0xf5, 0x4d, 0x3d, 0x82, 0xa8, 0x12, 0x42, 0x6f, 0x95, 0xf3, 0x76, 0xaf, 0xf3, 0x9c, 0xc1,
	0xcd, 0x9c, 0x61, 0x3b, 0x27, 0x7a, 0x0b, 0xb1, 0xda, 0xb3, 0xad, 0xfe, 0xc6, 0x4a, 0x95, 0xdc,
	0x65, 0x5e, 0x7e, 0x4f, 0x3a, 0x02, 0x7f, 0x80, 0xa7, 0xcb, 0xca, 0x76, 0x7b, 0xcf, 0x10, 0xfd,
	0xb0, 0x44, 0xe2, 0x65, 0x41, 0xfe, 0x7a, 0xf2, 0x58, 0xb4, 0xf7, 0xb2, 0x89, 0xc4, 0x85, 0x9b,
	0x15, 0xb6, 0x62, 0x7e, 0xb3, 0x42, 0x74, 0x65, 0xce, 0x8d, 0xf9, 0xe4, 0x8f, 0x0f, 0x63, 0x75,
	0x52, 0x3f, 0x99, 0x12, 0xd5, 0x62, 0x57, 0x2d, 0xf5, 0x4a, 0xd3, 0x4f, 0xfb, 0xd5, 0xe1, 0x40,
	0x39, 0x9a, 0x01, 0x74, 0x87, 0x44, 0xe3, 0xae, 0xec, 0xd5, 0x37, 0x91, 0x26, 0xfd, 0x01, 0x25,
	0xf1, 0x2b, 0xf4, 0x11, 0xe2, 0xf6, 0x6a, 0x68, 0xf4, 0x4f, 0xa2, 0x3b, 0x75, 0x3a, 0xee, 0xe5,
	0xad, 0xfe, 0x33, 0x3c, 0x10, 0x7a, 0x6c, 0xbb, 0xbe, 0xb6, 0xe8, 0xf6, 0x94, 0xa6, 0xfd, 0xfc,
	0xa5, 0x0b, 0x7f, 0xc9, 0x85, 0xff, 0xc7, 0x85, 0x37, 0x2e, 0xf3, 0x67, 0x78, 0xc3, 0x44, 0xb1,
	0xab, 0xe4, 0xa6, 0x38, 0x6f, 0xac, 0xcd, 0x9f, 0xb7, 0xff, 0xcc, 0x57, 0x6f, 0x1d, 0x59, 0x3c,
	0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x40, 0x89, 0x07, 0x52, 0x58, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SysvisorMgrStateChannelClient is the client API for SysvisorMgrStateChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SysvisorMgrStateChannelClient interface {
	// Subuid(gid) allocation request
	SubidAlloc(ctx context.Context, in *SubidAllocReq, opts ...grpc.CallOption) (*SubidAllocResp, error)
	// Subuid(gid) freeing request
	SubidFree(ctx context.Context, in *SubidFreeReq, opts ...grpc.CallOption) (*SubidFreeResp, error)
	// Supplementary mount request
	ReqSupMounts(ctx context.Context, in *SupMountsReq, opts ...grpc.CallOption) (*SupMountsReqResp, error)
	// Supplementary mount release
	RelSupMounts(ctx context.Context, in *SupMountsRel, opts ...grpc.CallOption) (*SupMountsRelResp, error)
}

type sysvisorMgrStateChannelClient struct {
	cc *grpc.ClientConn
}

func NewSysvisorMgrStateChannelClient(cc *grpc.ClientConn) SysvisorMgrStateChannelClient {
	return &sysvisorMgrStateChannelClient{cc}
}

func (c *sysvisorMgrStateChannelClient) SubidAlloc(ctx context.Context, in *SubidAllocReq, opts ...grpc.CallOption) (*SubidAllocResp, error) {
	out := new(SubidAllocResp)
	err := c.cc.Invoke(ctx, "/protobuf.sysvisorMgrStateChannel/SubidAlloc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysvisorMgrStateChannelClient) SubidFree(ctx context.Context, in *SubidFreeReq, opts ...grpc.CallOption) (*SubidFreeResp, error) {
	out := new(SubidFreeResp)
	err := c.cc.Invoke(ctx, "/protobuf.sysvisorMgrStateChannel/SubidFree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysvisorMgrStateChannelClient) ReqSupMounts(ctx context.Context, in *SupMountsReq, opts ...grpc.CallOption) (*SupMountsReqResp, error) {
	out := new(SupMountsReqResp)
	err := c.cc.Invoke(ctx, "/protobuf.sysvisorMgrStateChannel/ReqSupMounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysvisorMgrStateChannelClient) RelSupMounts(ctx context.Context, in *SupMountsRel, opts ...grpc.CallOption) (*SupMountsRelResp, error) {
	out := new(SupMountsRelResp)
	err := c.cc.Invoke(ctx, "/protobuf.sysvisorMgrStateChannel/RelSupMounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysvisorMgrStateChannelServer is the server API for SysvisorMgrStateChannel service.
type SysvisorMgrStateChannelServer interface {
	// Subuid(gid) allocation request
	SubidAlloc(context.Context, *SubidAllocReq) (*SubidAllocResp, error)
	// Subuid(gid) freeing request
	SubidFree(context.Context, *SubidFreeReq) (*SubidFreeResp, error)
	// Supplementary mount request
	ReqSupMounts(context.Context, *SupMountsReq) (*SupMountsReqResp, error)
	// Supplementary mount release
	RelSupMounts(context.Context, *SupMountsRel) (*SupMountsRelResp, error)
}

// UnimplementedSysvisorMgrStateChannelServer can be embedded to have forward compatible implementations.
type UnimplementedSysvisorMgrStateChannelServer struct {
}

func (*UnimplementedSysvisorMgrStateChannelServer) SubidAlloc(ctx context.Context, req *SubidAllocReq) (*SubidAllocResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubidAlloc not implemented")
}
func (*UnimplementedSysvisorMgrStateChannelServer) SubidFree(ctx context.Context, req *SubidFreeReq) (*SubidFreeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubidFree not implemented")
}
func (*UnimplementedSysvisorMgrStateChannelServer) ReqSupMounts(ctx context.Context, req *SupMountsReq) (*SupMountsReqResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqSupMounts not implemented")
}
func (*UnimplementedSysvisorMgrStateChannelServer) RelSupMounts(ctx context.Context, req *SupMountsRel) (*SupMountsRelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RelSupMounts not implemented")
}

func RegisterSysvisorMgrStateChannelServer(s *grpc.Server, srv SysvisorMgrStateChannelServer) {
	s.RegisterService(&_SysvisorMgrStateChannel_serviceDesc, srv)
}

func _SysvisorMgrStateChannel_SubidAlloc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubidAllocReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysvisorMgrStateChannelServer).SubidAlloc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.sysvisorMgrStateChannel/SubidAlloc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysvisorMgrStateChannelServer).SubidAlloc(ctx, req.(*SubidAllocReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysvisorMgrStateChannel_SubidFree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubidFreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysvisorMgrStateChannelServer).SubidFree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.sysvisorMgrStateChannel/SubidFree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysvisorMgrStateChannelServer).SubidFree(ctx, req.(*SubidFreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysvisorMgrStateChannel_ReqSupMounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupMountsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysvisorMgrStateChannelServer).ReqSupMounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.sysvisorMgrStateChannel/ReqSupMounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysvisorMgrStateChannelServer).ReqSupMounts(ctx, req.(*SupMountsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysvisorMgrStateChannel_RelSupMounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupMountsRel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysvisorMgrStateChannelServer).RelSupMounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.sysvisorMgrStateChannel/RelSupMounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysvisorMgrStateChannelServer).RelSupMounts(ctx, req.(*SupMountsRel))
	}
	return interceptor(ctx, in, info, handler)
}

var _SysvisorMgrStateChannel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.sysvisorMgrStateChannel",
	HandlerType: (*SysvisorMgrStateChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubidAlloc",
			Handler:    _SysvisorMgrStateChannel_SubidAlloc_Handler,
		},
		{
			MethodName: "SubidFree",
			Handler:    _SysvisorMgrStateChannel_SubidFree_Handler,
		},
		{
			MethodName: "ReqSupMounts",
			Handler:    _SysvisorMgrStateChannel_ReqSupMounts_Handler,
		},
		{
			MethodName: "RelSupMounts",
			Handler:    _SysvisorMgrStateChannel_RelSupMounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf.proto",
}
